style: Capitalize description of --help
punk-security/dnsReaper pull request #85
Opened 2022-08-09 12:15 UTC by Engr-Asad-Hussain

Found that the description of all inline options (arguments) is uniform except --help option. Capitalized the description of --help command also. 
```diff
options:
-  -h, --help            show this help message and exit
+  -h, --help            Show this help message and exit
  --out OUT             Output file (default: results) - use 'stdout' to stream out
  --out-format {csv,json}
  --parallelism PARALLELISM
                        Number of domains to test in parallel - too high and you may see odd DNS results (default: 30)
  --disable-probable    Do not check for probable conditions
  --enable-unlikely     Check for more conditions, but with a high false positive rate
...
```

2022-08-09 12:50 UTC, imnotbrandon commented
Hey, thanks for the contribution.
Those options are defined in `argparsing.py` and we use the auto generated help output in the readme file. Could you update this in `argparsing.py` please?

2022-08-09 12:51 UTC, imnotbrandon requested changes
Please update `argparsing.py` as this output is generated.

2022-08-09 15:51 UTC, Engr-Asad-Hussain commented
> Hey, thanks for the contribution. Those options are defined in `argparsing.py` and we use the auto generated help output in the readme file. Could you update this in `argparsing.py` please?

Thanks @imnotbrandon. I will update `argparsing.py` file and push the changes.

2022-08-09 17:22 UTC, Engr-Asad-Hussain commented
Hey, @imnotbrandon hope you are doing well. 
I have just made a minor change in `argparsing.py`. The `add_help=True` is by default in `class argparse.ArgumentParser` that's why it was generating the --help description. I have added another argument that works same as --help command but with custom help description/details. I have also attached the console print as an jpg file. [References](https://docs.python.org/2/library/argparse.html#add-help)
![2](https://user-images.githubusercontent.com/57555839/183716744-f50da071-c0c2-4365-8aa4-94e15b3800af.JPG)

2022-08-10 08:17 UTC, imnotbrandon approved these changes
Thanks for the contribution!

2022-08-10 10:57 UTC, Asad-Hussain98 commented
Your welcome! :sunglasses:

2022-08-10 11:04 UTC, imnotbrandon commented
Because the commits are not signed, only an admin can merge this.
@SimonGurney could you take a look please.

2022-08-10 11:33 UTC, Engr-Asad-Hussain commented
@imnotbrandon Your Welcome!

2022-08-10 14:04 UTC, SimonGurney approved these changes
The commits need squashing :)

2022-08-10 14:05 UTC, SimonGurney commented
I can't merge either, @imnotbrandon can you pull the branch and squash into one signed commit?

2022-08-10 14:15 UTC, imnotbrandon commented
I've had to squash and sign your commits because we only allow verified commits. You'll still get the contribution, however the pull request is now here: https://github.com/punk-security/dnsReaper/pull/90

2022-08-10 14:15 UTC, closed without merging